config/routes.rb
Newsly::Application.routes.draw do

  match "login-required" => "home#login_required", :as => "login_required"

  twitter = Newsly::Application.config.twitter_login
  twitter_endpoint = twitter.login_handler(:return_to => '/twitter-return')

  mount twitter_endpoint => 'login', :as => :login

  match "twitter-return" => "home#twitter_return"
  match "logout" => "home#twitter_logout", :as => "logout"

  root :to => "home#index"

  match "search/:q" => "search#search", :as => "search"
  match "search" => "search#router", :as => "search_router"

  match "about" => "home#about"

  match "keep-alive/:q" => "search#keepalive", :as => "keep_alive"

end

app/controllers/search_controller.rb
require 'digest/md5'

class SearchController < ApplicationController
	
	def router
		if !params[:q].blank?
			redirect_to search_path(params[:q]), :status => 301
		else
			redirect_to root_path
		end
	end

	def search

		@q = params[:q]
		@q = @q.strip
		@page_title = "#{@q}<span class='title-extra'> - Crisis.ly</span>".html_safe
		@qtag = Digest::MD5.hexdigest(@q)
		@old_tweets = REDIS.lrange "archive:#{@qtag}", 0, 40

		@tweet_text = "Get realtime news, filtered for accuracy"
   		@tweet_tags = "crisisly," + @q.gsub("#", "")
    	
		@template = File.open(Rails.root + "app/views/search/_tweet.html.erb", "rb").read

		@template = @template.gsub(".html_safe", "")
		if logged_in?

			@node_channel = Digest::MD5.hexdigest("#{current_user.to_s}:#{@q}")

			
			#Lets get this user tracking it.
			REDIS.setex "track:#{current_user.to_s}:#{@qtag}", 3.minutes, @q

			REDIS.setex "track:___keepalive:#{current_user.to_s}", 3.minutes, "yes"
			REDIS.setex "track:___changed:#{current_user.to_s}", 3.minutes, "yes"
			#Lets add it to our currently being tracked list
			REDIS.lpush "trending", @q
			
			#Lets add this user to the people tracking it
			REDIS.lpush "tracking:#{@qtag}", current_user.id
			#Lets issue a pub notice to our users channel to make sure we have a worker forked
			REDIS.publish "workers", current_user.to_s

		else
			#if no old tweets, redirect to the login page
			if @old_tweets.blank?
				redirect_to login_required_path
			end

			@node_channel = Digest::MD5.hexdigest("guest:#{@q}")
		end
		

	end

	def keepalive
		@q = params[:q]
		@q = @q.strip

		@qtag = Digest::MD5.hexdigest(@q)
		REDIS.setex "track:#{current_user.to_s}:#{@qtag}", 3.minutes, @q

		REDIS.setex "track:___keepalive:#{current_user.to_s}", 3.minutes, "yes"

		render :text => "ok"
	end
end

app/views/search/_tweet.html.erb
<div class="tweet" id="<%= this.web_id %>" style="display:none;">
	<div class="tweet-img">
		<a href="http://twitter.com/<%= this.account %>" title="Follow <%= this.account %>">
		<img src="<%= this.imgurl %>" alt="<%= this.account %>" />
		</a>
		
	</div>

	<div class="tweet-text">
		<div class="tweet-meta">
			<strong><%= this.account %></strong> - relevance score <%= this.pure_score %>
		</div>
		<%= this.html.html_safe %>
	</div>
	
</div>

app/views/search/search.html.haml
:javascript
	$(document).ready(function() {
		$("#loading").spin("large");

		var socket = io.connect('http://#{request.host}:8080');
		socket.on('#{@node_channel}', function (data) {
			datum = $.parseJSON(data['data']);
			console.log(datum);
			max_minutes = 5;

			$("#loading-box").hide(function() {
				$("#loading-box").remove();
			});

			$("#archive").fadeOut(800, function (){
				$("#archive").remove();

			});


			$("#rank_" + datum['pure_score']).prepend(
				$("#tweettemplate").jqote( datum )
			);
			$("#" + datum['web_id']).fadeIn(1000).delay(parseInt(datum['expire_in']) * max_minutes).fadeOut(2000, function() {
				$(this).remove();
			});

		});


		(function worker() {
			$.ajax({
				url: '#{keep_alive_url(@q)}', 
				success: function(data) {
					
				},
				complete: function() {
					setTimeout(worker, 60000);
				}
			});
		})();

		$("#archive .tweet").fadeIn(1000);

		

	});

#loading-box
	#loading
	%p 
		Engaging warp drive...
		%br
		= "(Waiting for someone to tweet about #{@q})"
		- if !logged_in?
			= link_to "&raquo; login with Twitter for realtime tweets &laquo;".html_safe, "/login"


#incoming
	- 100.times do |i|
		.rank{:id => "rank_#{100 - i}"}

#archive
	- @old_tweets.each do |tweet|
		= render :partial => "tweet", :locals => {:this => ArchiveTweet.new(tweet)}

:erb
	<script id="tweettemplate" type="text/x-jqote-template">
		<![CDATA[
			<%= @template %>
		]]>
	</script>