config/routes.rb
Newsly::Application.routes.draw do

  match "login-required" => "home#login_required", :as => "login_required"

  twitter = Newsly::Application.config.twitter_login
  twitter_endpoint = twitter.login_handler(:return_to => '/twitter-return')

  mount twitter_endpoint => 'login', :as => :login

  match "twitter-return" => "home#twitter_return"
  match "logout" => "home#twitter_logout", :as => "logout"

  root :to => "home#index"

  match "search/:q" => "search#search", :as => "search"
  match "search" => "search#router", :as => "search_router"

  match "about" => "home#about"

  match "keep-alive/:q" => "search#keepalive", :as => "keep_alive"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	caches_action :index, :expires_in => 60.seconds, :public => true, :if => Proc.new { !logged_in? && flash.blank? }
	caches_action :login_required, :expires_in => 60.seconds, :if => Proc.new { !logged_in? && flash.blank? }
	caches_action :about, :expires_in => 600.seconds, :if => Proc.new { !logged_in? && flash.blank? }
	def index
		trending = REDIS.lrange("trending", 0, 20).uniq
		@trending = {}
		trending.each do |trend|
			trackers = []
			hsh = Digest::MD5.hexdigest(trend)
			trckrs = REDIS.lrange "tracking:#{hsh}", 0, 10
			trckrs.each do |t|
				trackers << User[t.to_i]
			end
			@trending[trend] = trackers.uniq
		end
		feeds = Rails.cache.fetch("latest_feed", :expires_in => 1.hour) do 
			Feedzirra::Feed.fetch_and_parse(["https://api.twitter.com/1/lists/statuses.atom?slug=breakingnews&owner_screen_name=palafo&per_page=100&page=1&include_entities=true", "https://api.twitter.com/1/lists/statuses.atom?slug=breakingnews&owner_screen_name=palafo&per_page=100&page=2&include_entities=true"])
		end
		@feed = []
		begin
			feeds.each do |k,feed|
				feed.entries.each do |f|
					if f.title.include?("#")
						@feed << f
					end
				end
			end
		rescue
			@feed = []
		end
	end

	def about
		@page_title = "About Crisis.ly"
	end

	def twitter_return
		if !twitter_user.id.blank?
			u = User.find(:twitter_id => twitter_user.id)
			if u.blank?
				u = User.create(:twitter_id => twitter_user.id)
			else
				u = u.first
			end

			temp = twitter_user.to_hash
			temp.delete "id"
			temp.delete "id_str"
			u.update(temp)

			temp = JSON.parse twitter_client.get("/1/users/show.json?user_id=#{twitter_user.id}").body
			logger.info temp

			[:profile_image_url].each do |key|
				u.update(key => temp[key.to_s])
			end

			#u.update(temp)

			u.twitter_key = twitter_oauth.key
			u.twitter_secret = twitter_oauth.secret
			u.twitter_token = twitter_client.token
			u.twitter_token_secret = twitter_client.secret
			u.save

			session[:current_user] = u.screen_name
				
			flash[:notice] = "Welcome #{u.name}! You can now access realtime tweets."
			

		end
		redirect_to "/"
	end
	def login_required
		@page_title = "Login required"
	end
end

app/views/home/about.html.haml
#strap-line So, what's this all about then?
.about
	%br
	%br
	%p
		Hi. Crisis.ly started as a weekend hack project, me playing around with some new technologies I wanted to explore, and got to what you see now with me deciding to actually go the last 20% with it and put it out into the real world. I'm <a href="http://www.danhilltech.com/">Dan, co-founder and CTO</a> at <a href="http://www.crashpadder.com">Crashpadder.com</a> - a project we've been working on for about <a href="http://www.crashpadder.com/press">3 years now</a>. 
	%p
		Crisis.ly aims to take the realtime Twitter stream for a breaking news story, and instead of displaying tweets chronologically (like a <a href="http://www.google.com/?q=Tweet%20Wall">Tweet Wall</a>) it displays them in a combination of recency and relevance/authority. I built a simple (for now) algorithm to rank a tweet's authority - how many followers they have, how many retweets, it's geographical proximity to other tweets, keyword density, how far you are from them on a Twitter <a href="http://en.wikipedia.org/wiki/Erd%C5%91s%E2%80%93Bacon_number">Erd&#x0151;s-Bacon</a> graph, and so on.
	%p
		On the techie side, it's using <a href="http://rubyonrails.org/">Rails 3.1</a>, <a href="http://nodejs.org/">Node.js</a>, <a href="http://redis.io">Redis</a>, Resque, the Twitter realtime APIs, nginx, EC2, Github, and some other cool things. And no SQL in sight - nice.
	%p
		<a href="https://twitter.com/serenestudios" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @serenestudios</a> <a href="https://twitter.com/crisisly" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @crisisly</a>

app/views/home/index.html.haml
#strap-line
	Realtime social news, filtered for accuracy and quality

#search-box
	= form_tag(search_router_path) do
		#q-box
			= text_field_tag(:q, nil, :placeholder => "Search...")

#tripartite
	.tabcontent
		%h3 Trending Now
		- @trending.each do |trend, trackers|
			%p.trending-topic
				= link_to trend, search_path(trend)
				= " - " 
				- trackers.each do |tracker|
					~ link_to image_tag(tracker.profile_image_url, :size => "20x20"), "http://twitter.com/#{tracker.screen_name}", :target => "_blank"
	.tabcontent
		%h3 Explore News
		- @feed[0..4].each do |item|
			- unless extract_hashtags(item.title).count == 0
				.tweet
					.tweet-img
						= link_to image_tag(item.links.second), search_path("#" + extract_hashtags(item.title).first)
					.tweet-text
						= crisisly_link item.title
	.tabcontent.tabcontent-last
		%h3 About
		%p 
			Crisis.ly is a tool to filter the Twitter firehose by relevance and importance, rather than purely chronologically. It is built by 
			= link_to("Dan Hill", "http://twitter.com/serenestudios") + "," 
			= link_to "CTO at Crashpadder.com", "http://www.crashpadder.com"
			in a few weekends, as a way to play with some new toys:
		%br
		%ul 
			%li Rails 3.1
			%li HTML5
			%li Responsive design
			%li Node.js
			%li realtime Twitter APIs.
		%p= link_to "Read more &raquo;".html_safe, about_path

app/views/home/login_required.html.haml
#strap-line
	You need to login to access realtime news
	%br
	%br	
	= link_to "Login with Twitter", "/login", :class => 'button'

.midscreenprompt
	%p In order to get realtime updates you need to login with Twitter. We won't do anything with your details, or tweet on your belhalf.