config/routes.rb
Newsly::Application.routes.draw do

  match "login-required" => "home#login_required", :as => "login_required"

  twitter = Newsly::Application.config.twitter_login
  twitter_endpoint = twitter.login_handler(:return_to => '/twitter-return')

  mount twitter_endpoint => 'login', :as => :login

  match "twitter-return" => "home#twitter_return"
  match "logout" => "home#twitter_logout", :as => "logout"

  root :to => "home#index"

  match "search/:q" => "search#search", :as => "search"
  match "search" => "search#router", :as => "search_router"

  match "about" => "home#about"

  match "keep-alive/:q" => "search#keepalive", :as => "keep_alive"

end

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_footer.html.haml
	

#browser-top-right
	%a{:href => "https://twitter.com/share", :class => "twitter-share-button", "data-text" => @tweet_text, "data-via" => "crisisly", "data-related" => @tweet_should_follow.join(","), "data-hashtags" => @tweet_tags}

#browser-bottom-right
	= link_to "about", about_path
	|
	= link_to "home", root_path
	|
	- if logged_in?
		= current_user.to_s
		|
		= link_to "logout", logout_path
	- else
		= link_to "login with Twitter", "/login"

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title= strip_tags @page_title
  
%meta{ :name => "description", :content => @page_description}/
%meta{ :name => "author", :content => "Dan Hill - www.danhilltech.com" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/
%meta{ :name => "apple-mobile-web-app-capable", :content => "yes" }/
%meta{ :name => "apple-mobile-web-app-status-bar-style", :content => "default" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

%link{ :href => 'http://fonts.googleapis.com/css?family=Open+Sans:300,600|Vollkorn', :rel => 'stylesheet', :type => 'text/css'}


-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag 'modernizr.min.js', 'respond.min.js'



= csrf_meta_tag

app/views/layouts/_header.html.haml
= link_to "Home", root_path, :id => "mobile_home", :class => 'navbutton'

%h1#page-title= @page_title

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.7") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.7") }"

-# fall back to local jQuery if necessary
:javascript
  $(function() {
    $("#main").css("margin-top", $("#header").height() + 15);
    /Mobile/.test(navigator.userAgent) && !location.hash && setTimeout(function () {
      if (!pageYOffset) window.scrollTo(0, 1);
    }, 200);

    if($("#browser-bottom-right").css("display") == "block") {
      $("#browser-bottom-right").hide();
      $("#browser-bottom-right").fadeIn(2000);
    }

    $("#flash").fadeOut(5000);

  });
  
= javascript_include_tag 'rails', 'plugins', 'application', 'socket', 'jqote', 'spin'
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"],["_trackPageLoadTime"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    -# To render a different stylesheet partial inside the head (i.e. for admin layout)
    -# just copy _stylesheets.html.haml, and point to that partial instead.
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
    = render "layouts/javascripts"
  %body{ :class => "#{controller.controller_name}" }
    #container
      %header#header.toolbar
        = render "layouts/header"
        
      #main{ :role => 'main' }
        #main-inner
          = render "layouts/flashes"
          = yield
        
      %footer#footer
        = render "layouts/footer"
        
    -# Javascript at the bottom for fast page loading
    